Repository plonegovbr/brasil.gov.temas, pull requests merged in 2018-08, with the labels that each got.

#198 Finalização das variáveis do tema
  webpack/app/branco/brasilgovtemas.scss
  webpack/app/branco/sprite/lista-seta.png
  webpack/app/padrao/brasilgovtemas.scss
  webpack/app/padrao/sprite/lista-seta.png
  webpack/app/scss/_basic.scss
  webpack/app/scss/_content.scss
  webpack/app/scss/_tiles.scss
Labels: 2.x, enhancement, ready

#201 Estilos para a variação do topo
  CHANGES.rst
  webpack/app/brasilgovtemas.js
  webpack/app/index-minimalista.html
  webpack/app/index.html
  webpack/app/rules.xml
  webpack/app/scss/_header.scss
Labels: ready

#203 Add Content Central View
  CHANGES.rst
  webpack/app/branco/brasilgovtemas.scss
  webpack/app/brasilgovtemas.js
  webpack/app/js/contentcentral.js
  webpack/app/padrao/brasilgovtemas.scss
  webpack/app/scss/_contentcentral.scss
Labels: 2.x, in progress

#202 Add Filter Results View
  CHANGES.rst
  webpack/app/branco/brasilgovtemas.scss
  webpack/app/brasilgovtemas.js
  webpack/app/js/resultsfilter.js
  webpack/app/padrao/brasilgovtemas.scss
  webpack/app/scss/_content.scss
  webpack/app/scss/_contrast.scss
  webpack/app/scss/_resultsfilter.scss
  webpack/app/scss/_search.scss
Labels: 2.x, in progress
